language: generic

sudo: required
services:
    - docker

before_install:
    - docker build -t parashar1505/docker-react -f Dockerfile.dev .

scripts:
    - docker run -e CI=true parashar1505/docker-react npm run test

deploy:
    edge: true
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-us-east-2-013106688149"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY